version: 2.1

executors:
  ruby-executor:
    parameters:
      version:
        type: string
    docker:
      - image: ruby:<< parameters.version >>
        environment:
          REDIS_URL: redis://127.0.0.1:6379
      - image: cimg/redis:6.2
    working_directory: ~/fruit_juice

jobs:
  test:
    executor:
      name: ruby-executor
      version: << parameters.ruby-version >>
    parameters:
      ruby-version:
        type: string
    steps:
      - checkout
      # Delete the Gemfile.lock for the older out of date ruby versions
      - run:
          name: Conditionally remove Gemfile.lock
          command: |
            if [[ "<< parameters.ruby-version >>" < "2.6" ]]; then
              rm Gemfile.lock
              rm gemfiles/redis_4.gemfile.lock
              rm gemfiles/redis_5.gemfile.lock
            fi
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Install appraisal dependencies
          command: bundle exec appraisal install
      - run:
          name: Run specs
          command: bundle exec appraisal rspec
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  fruit_juice_specs:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.2.3", "2.5.0", "2.7.4", "3.2.2", "3.3.0-preview1"]