version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.4.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  ruby-3-2-0:
    docker:
      - image: cimg/ruby:3.2.0
      - image: cimg/redis:6.2
        environment:
          REDIS_URL: redis://localhost:6379
    executor: ruby/default
    working_directory: ~/fruit_juice
    steps:
      - checkout
      - run:
          name: Create test result folder
          command: |
            mkdir ~/fruit_juice/test-results
            touch test-results/test.log
      - run:
          name: Which bundler?
          command: bundle -v
      - run: 
          name: Install appraisal
          command: gem install appraisal
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Install appraisal dependencies
          command: appraisal install
      - run:
          name: Run specs
          command: appraisal rspec
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  ruby-2-5-4:
    docker:
      - image: cimg/ruby:2.5.4
      - image: cimg/redis:6.2
        environment:
          REDIS_URL: redis://localhost:6379
    executor: ruby/default
    working_directory: ~/fruit_juice
    steps:
      - checkout
      - run:
          name: Create test result folder
          command: |
            mkdir ~/fruit_juice/test-results
            touch test-results/test.log
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run specs
          command: bundle exec rspec \
            --format documentation \
            --format progress \
            --out test-results/progress_output.txt \
            --format RspecJunitFormatter \
            --out test-results/rspec-test-results/rspec.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  fruit_juice_specs: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - ruby-3-2-0
      - ruby-2-5-4
