version: 2.1

executors:
  ruby-executor:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.version >>
      - image: cimg/redis:6.2
        environment:
          REDIS_URL: redis://localhost:6379
    working_directory: ~/fruit_juice

jobs:
  test:
    executor:
      name: ruby-executor
      version: << parameters.ruby-version >>
    parameters:
      ruby-version:
        type: string
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Install appraisal
          command: bundle exec gem install appraisal
      - run:
          name: Install appraisal dependencies
          command: bundle exec appraisal install
      - run:
          name: Run specs
          command: bundle exec appraisal rspec
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  fruit_juice_specs:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.2.2", "2.3.0", "2.4.0", "2.5.4", "3.2.0", "latest"]